# Generated by Django 4.2.6 on 2024-11-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=30, verbose_name='部屋タイプ')),
                ('Reservation_date', models.DateField(auto_now=True, verbose_name='予約日付')),
            ],
        ),
    ]
